//
//  ListAritclesPresenter.swift
//  Assessment
//
//  Created Heema Boss on 5/26/20.
//  Copyright © 2020 Ibraheem. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ListAritclesPresenter: ListAritclesPresenterProtocol {
    
    weak private var view: ListAritclesViewProtocol?
    var interactor: ListAritclesInteractorProtocol?
    private let router: ListAritclesWireframeProtocol
    var lastaritcles: AritclesEntity?
    
    init(interface: ListAritclesViewProtocol, interactor: ListAritclesInteractorProtocol?, router: ListAritclesWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func viewDidLoad() {
        getListAritcles()
    }
    
    func titleVC() -> String{
        return "NY Times Most Populr"
    }
    
    private func getListAritcles(){
        interactor?.getListAritcles()
    }
    
    func aritclesLoaded(aritcles: AritclesEntity?){
        self.lastaritcles = aritcles
        view?.populateTableView()
    }
    
    func aritclesLoadingError(error: String){
        print(error)
    }
}
