//
//  ListAritclesRouter.swift
//  Assessment
//
//  Created Heema Boss on 5/26/20.
//  Copyright © 2020 Ibraheem. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ListAritclesRouter: ListAritclesWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        
        // Change to get view from storyboard if not using progammatic UI
        let view = R.storyboard.listAritcles.listAritclesViewController()!
        let interactor = ListAritclesInteractor()
        let router = ListAritclesRouter()
        let presenter = ListAritclesPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
